### PR TITLE
Refresh credentials

### PR DESCRIPTION
**Pull request by divergentdave**
This builds on PR #1, adding semi-automated tests running on AWS Cloudformation. See test/README.md for instructions and explanation. Let me know what you think!

### CODE REVIEW

**Comment by TheDeveloper** [comment]
Thanks @divergentdave! I will take a look

**Comment by TheDeveloper** [comment]
@divergentdave I've taken a look through this. Excellent work. I've been polishing up the new connector code this evening and have been testing with the CloudFormation Stack. Unfortunately I've run out of time before I could finish a release, but I'll get onto that next spare moment I get. Hopefully early next week.

FYI I hit a couple of snags running the `runtests` script for the first time. It expects the S3 bucket to exist in order to upload the zip, which isn't the case when you haven't yet set up the CF stack. The other issue was the `aws-sdk` and `archiver` packages are required in at the top of the script, which also don't exist if you haven't yet got `test/node_modules` installed.

I've worked around these issues and I'll look to correct them when I pick this back up, unless you get there first 😄

**Comment by TheDeveloper** [comment]
@divergentdave I have pushed my progress so far to https://github.com/TheDeveloper/http-aws-es/tree/credential-providers - including workaround for first run of `runtests`. note: I created the S3 bucket manually. A more robust solution is needed but this got around the problems for now.

**Comment by divergentdave** [comment]
Yeah, my intent was for the S3 bucket to be manually created before running the script. This is mentioned in test/README.md under "Prerequisites." I didn't want to create the bucket from inside the Cloudformation stack, for fear of setting up a race between uploading the code and the Lambda/EC2 resources coming up. Plus everyone needs to have their own bucket name, and I wasn't comfortable rolling my own autogenerated names.

Good call on `test/node_modules`, I'll add `npm install` to the docs as well.

**Comment by TheDeveloper** [comment]
@divergentdave my bad, I missed that prerequisite. That's fair enough. Thanks for the extensive readme as well.

I'm planning to put together a local test suite to run the connector in a local environment as well (against a pre-provisioned Amazon ES resource). This will make testing development faster and then the full CF stack can be brought up to test more complete versions in AWS environment.

**Comment by divergentdave** [comment]
Sounds great. Yeah, the CF stack is pretty ponderous. I found that both setting up and tearing down the ES domain inside the stack took at least 15 minutes.

**Pull request closed without merging**
