### PR TITLE
Update babel prepublish in package.json

### PR DESCRIPTION
**Pull request by py09mb**
Master branch wasn't creating the transpiled connector.js file on install. Updated to the newest babel and updated the prepublish command line.

### CODE REVIEW

**Comment by tielur** [comment]
:+1:

**Comment by TheDeveloper** [comment]
@py09mb Thanks for this. Not quite sure what's being fixed though.

Master prepublish script seems to work fine for me. Did you say the connector.js file was missing on install? It should get packed up when the module is published.

**Comment by tielur** [comment]
@TheDeveloper I can confirm that the `connector.js` is in a the package. I did notice that previously in the past it was not though. I'm not sure what changed.

**Comment by tielur** [comment]
FWIW, I just installed and checked all of the previous versions published and they all contain the `connector.js`. Not sure what I've experienced then.

Confirmed these versions all had `connector.js`: `'1.0.0', '1.0.1', '1.0.2', '1.1.0', '1.1.1', '1.1.2', '1.1.3'`

**Comment by py09mb** [comment]
Must have been some unrelated issue, for me the package was all fine when developing locally but when our build was running connector.js was missing and I had to manually run babel to transpile from the es6 code.

**Pull request closed without merging**
