### PR TITLE
Depend on elasticsearch-js 14.2.0 instead of 13.2.0

### LINKED ISSUE #49: Support for elasticsearch ^14.0

### PR DESCRIPTION
**Pull request by laurie-qlik**
Fixes https://github.com/TheDeveloper/http-aws-es/issues/49
=> Updates version number to 5.0.0

### CODE REVIEW

**Comment by mike-weshop** [comment]
Would be good to get this merged in, if possible.

**Comment by austinkelleher** [comment]
@TheDeveloper can we please get this merged?

**Comment by danielmcq** [comment]
FYI, elasticsearch now has a version 15.0.0. Here's the changelog: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog.html

**Comment by mike-weshop** [comment]
Thanks 👍

**Pull request merged**
