### PR TITLE
change out AWS signer for the aws4 signer package

### PR DESCRIPTION
**Pull request by brewdium**
Hi there,

I was having some trouble using this package with the loopback elasticsearch connector (https://github.com/strongloop-community/loopback-connector-elastic-search) and tracked downt he problem to the `AWS.Signers.V4`. Documentation on that isn't real great at the moment (aws not recommending it's use right now?) so I simply switched it out for the aws4 node package and it fixed my problem.

I haven't really done much testing with it but I probably can do if you are interested in pulling this in. If you'd prefer to stick with the aws signers I understand, just decline this, but I thought I may as well throw in this PR just in case.

Thankyou

### CODE REVIEW

**Comment by TheDeveloper** [comment]
Thanks for this!

Do you have any more info around why the aws signer was failing?

We have seen a few reports of auth errors but not exactly clear if due to misconfiguration or aws signer problems.

**Comment by spazworm** [comment]
I'm not too sure sorry, I was going to use Charles to compare the working and non working branches to see what has changed about the requests but I haven't had the time as of yet.

**Comment by spazworm** [comment]
I also noticed that loopback-connector-es might not be passing through the config correctly, it's more something I should comment to them but I thought I better mention it just in case you were confused by the commit.

**Comment by eviltwin** [comment]
This change also solves the issue for us.

For reference, the call to `signer.addAuthorization(creds, new Date());` in `HttpAmazonESConnector#signRequest` is throwing this error (which incidentally goes uncaught and and the promise never resolves):

```
ERROR TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hmac.Hash.update (crypto.js:74:16)
    at Object.hmac (/opt/app/node_modules/aws-sdk/lib/util.js:401:50)
    at Object.getSigningKey (/opt/app/node_modules/aws-sdk/lib/signers/v4_credentials.js:71:35)
    at V4.signature (/opt/app/node_modules/aws-sdk/lib/signers/v4.js:97:36)
    at V4.authorization (/opt/app/node_modules/aws-sdk/lib/signers/v4.js:92:36)
    at V4.addAuthorization (/opt/app/node_modules/aws-sdk/lib/signers/v4.js:34:12)
    at HttpAmazonESConnector.signRequest (/opt/app/node_modules/http-aws-es/connector.js:110:14)
    at getAWSCredentials.catch.then.creds (/opt/app/node_modules/http-aws-es/connector.js:65:14)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by compwright** [comment]
Reference: https://github.com/aws/aws-sdk-js/issues/1247

**Pull request closed without merging**
